# External gems
gems:
  - jekyll-sitemap

exclude:
  - "/vendor/"

# Site settings
title: Sussex Mindfulness Centre
subtitle:
name: Sussex Mindfulness Cent
description: Coming soon
# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
baseurl: ""
# the base hostname & protocol for your site
url: "http://www.sussexmindfulness.nhs.uk"
logo: /assets/logo.png
email: support@eyedivision.com

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: false
permalink: pretty

# Image CDN
imagecdn:
  staging: "http://ed-smc-dev.imgix.net"
  production: "http://ed-smc.imgix.net"

# Collections
#collections:
#    projects:
#        output: true
#        permalink: /projects/:path/


# Defaults Example
defaults:
     - type: ''
       values:
         _comments:
          carousel: Update the slide show
#    -
#        scope:
#            path: ""
 #           type: "projects"
#        values:
 #           layout: "project"


# Google analytics
# ga_tracking_id: "UA-XXXX-1"


# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:
  - name: Twitter
    icon: twitter
    username:
    url:
    desc: Follow us on Twitter
    share: true

  - name: Facebook
    icon: facebook
    username:
    url:
    desc: Like us on Facebook
    share: true


  - name: YouTube
    icon: youtube
    username:
    url:
    desc: Subscribe on YouTube
    share: false


  - name: SoundCloud
    icon: soundcloud
    username:
    url:
    desc: Follow me on SoundCloud
    share: false

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "/assets/logo.png"

